# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
