# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
